platform :ios, '12.0'

target 'DejaVu' do
	use_frameworks!

	# UI
	pod 'SnapKit', '~> 4.0'
	
	# Database
	pod 'SQLite.swift', '~> 0.11.5'
	
	# Google Maps
	pod 'GoogleMaps', '~> 2.7'
	pod 'GooglePlaces', '~> 2.7'

	target 'DejaVuTests' do
		inherit! :search_paths
	end
end
